### ISSUE TITLE
Ensure that all `dplyr` and `tidyr` functions work

### ISSUE THREAD

**Issue by DavisVaughan** [business-science/tibbletime#1]
Don't want to lose class and attributes when using tidyverse functions.

**Comment by dmi3kno** [comment]
How about predicate functions: mutate_*, summarize_*?

**Comment by DavisVaughan** [comment]
@dmi3kno, I'll be pushing a complete rewrite to tibbletime to master here in the next few minutes. It makes it much more flexible in its interaction with dplyr and any dplyr function should be usable.

**Comment by DavisVaughan** [comment]
Closed by [e40156d](https://github.com/business-science/tibbletime/commit/e40156db0641cb0169e62a728c9710bbe832be38)
