### ISSUE TITLE
tmap_dfc() function error

### ISSUE THREAD

**Issue by allanbutler** [business-science/tibbletime#12]
mapped_df_means <- FANG %>%
  tmap_dfc(~mean(.x), period = "yearly")

Error in mutate_impl(.data, dots) : Evaluation error: 'map_dfc' is not an exported object from 'namespace:purrr'.

**Comment by DavisVaughan** [comment]
Are you using the most up to date version or purrr? Try `install.packages(purrr)` and try again. I think you need >0.2.3
