### ISSUE TITLE
 time_summarise / period   = "half-yearly" 

### ISSUE THREAD

**Issue by JoeFernando** [business-science/tibbletime#14]
Thanks for this library. It's very useful for me!

My first request is for inclusion of "half-yearly" time period.

Thanks in advance.
Kind regards,
Joe

**Comment by DavisVaughan** [comment]
@JoeFernando, thanks for the nice words. There is some active discussion on the topic of "generic periods" over in issue #9. This would allow you to do something like "every 6 months". It will definitely be a feature in the near future. I'm going to close this as I'd like to keep that discussion in one place. Thanks!
