### ISSUE TITLE
Add note to use sorted dates in README

### ISSUE THREAD

**Issue by DavisVaughan** [business-science/tibbletime#18]

**Comment by dmi3kno** [comment]
Lets work it out, so that it is not necessary to group FANG by ticker before processing. There's no way you can ensure that the data is sorted, so you can not possibly warn the user.

**Comment by DavisVaughan** [comment]
@dmi3kno, It is necessary to group FANG before using `time_group`. The time groups generated depend upon the dates inside the specific group. 

I don't plan on ensuring that the data is sorted. Its up to the user to use sorted data. The note in the readme will be near the top so that the user is aware that he/she needs to use sorted dates.

pandas datetime objects take a similar approach. The reason is for speed and complexity of checking if data is sorted, etc

**Comment by dmi3kno** [comment]
Had an idea that it may not be very expensive to assert that the index is sorted by comparing a sorted and unsorted version (`all.equal()`) inside `time_group()`. I understand the speed concern, but not issuing any warning is misleading.

As I am thinking of sorting assumption, base::merge comes to mind. Do you remember that it used to sort the data before merging, so you always had to watch out? Now, we could do the same, making a mandatory sort in time_collapse() (or even higher up) before grouping the periods. If you want to be super nice, you could think of storing the original order in .order variable and restoring (arranging by it) it before returning the tbl_time back to user.

**Comment by DavisVaughan** [comment]
Closed by #28
