### ISSUE TITLE
Issue with time_summarize

### ISSUE THREAD

**Issue by GreigR** [business-science/tibbletime#19]
Hi,

Thanks for the package. My problem the time_summarize() function does not seem to work if there is a time associated with the event date. It seems to work without the time at the designated level of weekly eg your FB example. In my data with the date & time, I get the summary function applied not to a weekly block but rather to the previous seven days. So if I count the number of widgets produced per week over a year then I get 365 results not 52.

Happy to accept I have misunderstood something or just generally screwed up my code.

Many thanks

Greig

**Comment by DavisVaughan** [comment]
Please provide a full reproducible example. I cannot help you otherwise!

**Comment by GreigR** [comment]
Hi Davis, as attached. Kind regards Greig
[Tibbletime_test.pdf](https://github.com/business-science/tibbletime/files/1378247/Tibbletime_test.pdf)

**Comment by dmi3kno** [comment]
Dear @GreigR ,

The example that you provided works fine for me and there's no discrepancy between `lubridate` and `tibbletime` method :) 

Please, be aware that `tibbletime` relies on several important assumptions:
1) Unless otherwise indicated, it uses ISO week numbers which may span year end. For example, 
```
> isoweek(as.Date("2012-12-31"))
[1] 1
> isoweek(as.Date("2013-01-01"))
[1] 1
```
You will not find a call to `isoweek()` directly, but `tibbletime` relies on `lubridate::floor_date()`, which in the context of weeks-based calculation, returns the beginning of the week:
```
> floor_date(as.Date("2013-01-01"), "weeks")
[1] "2012-12-30"
```
It is not clear from your example how you might have calculated `Arrival_year` and `Arrival_week`, but it is completely possible that those are not in fact ISO compliant weeks and therefore you are calculating totals over somewhat different groups.

PS: Have a look at this post about minimal reproducible example https://robjhyndman.com/hyndsight/minimal-reproducible-examples/

**Comment by GreigR** [comment]
Many thanks @dmi3kno,

Many thanks, especially for the minimal reproducible example reference. The year and week were calculated via lubridate functions year() and month() respectively. 

Kind regards

Greig

**Comment by dmi3kno** [comment]
@GreigR, Apologize for the joke. You did not provide the data, so it was impossible to reproduce your results. I believe there is a bug and I fixed it with my PR #21 .  Install from 
https://github.com/dmi3kno/tibbletime to compare,

Here's a reprex. It fails in the current version:

```
library(tibbletime)
data(FANG)

tibbletime_solution <- FANG %>% as_tbl_time(index = date) %>% 
  time_summarise(period = "weekly", n_week=n())

library(lubridate)
library(dplyr)

iso_yearweek <- function (x = Sys.Date()) {
  # borrowed from https://stackoverflow.com/questions/28543243/creating-a-year-week-format-for-current-date-in-r
  xday <- ISOdate(year(x), month(x), day(x), tz = tz(x))
  dn <- 1 + (wday(x) + 5)%%7
  nth <- xday + ddays(4 - dn)
  jan1 <- ISOdate(year(nth), 1, 1, tz = tz(x))
  return(sprintf("%s-%02d", format(nth, "%y"), 1 + (nth - jan1)%/%ddays(7)))
}

lubridate_solution <- FANG %>% 
  group_by(iso_yearweek(date)) %>% 
  group_by(date=max(date)) %>% 
  summarise(n_week=n()) 

all.equal(lubridate_solution, tibbletime_solution)
```

**Comment by GreigR** [comment]
Hi  @dmi3kno <https://github.com/dmi3kno>,

I am new at this git hub and bug chasing, so my apologies for making your
life harder. I have created a github repo with the data and files to
generate the results I was observing (github.com/GreigR/Tibble_test).

This has persisted despite your update to the tibbletime library. If I
index without a time on the date index all is well when I use
time_summarize. If I index my tibbletime object with a data that includes
time then the time_summarize function produces the wrong result.

Kind regards

Greig

**Comment by dmi3kno** [comment]
Pushed a fix to github. Try reinstalling with devtools::install_github("dmi3kno/tibbletime")

**Comment by DavisVaughan** [comment]
@GreigR, 

I've run the Rmd in `Tibble_test`. Your problem is coming from not having dates in order. Try to use `arrange()` first. `tibbletime` assumes your dates are in order.

```r
#Tibble time series

Tibble_data <- as_tbl_time(Test_data, index = Date_no_time)

Result_tibble <- Tibble_data %>% 
  arrange(Date_no_time) %>%
  time_summarise(
    period = "weekly",
    Count = n()
  )

glimpse(Result_tibble)
```

**Comment by GreigR** [comment]
Hi  @dmi3kno <https://github.com/dmi3kno>,

Many thanks, arrange() does work=k great with Date_no_time. The but is the
third example Date_with_time produces not the four results corresponding to
the four weeks. Rather it produces only some result which is a summation of
the four weeks.

Regards

Greig

**Comment by dmi3kno** [comment]
I am looking at it. 

@DavisVaughan , we need to have unit test for time_group() with `POSIXct` index

**Comment by DavisVaughan** [comment]
@GreigR I think it works for me?

```r
#Tibble time series with time

Tibble_data2 <- as_tbl_time(Test_data, index = Date_with_time)

Result_tibble2 <- Tibble_data2 %>% 
  arrange(Date_with_time) %>%
  time_summarise(
    period = "weekly",
    Count = n()
  )

glimpse(Result_tibble2)
```

```
Observations: 4
Variables: 2
$ Date_with_time <dttm> 2017-07-08 22:30:00, 2017-07-15 23:44:00, 2017-07-22 22:53:00, 20...
$ Count          <int> 767, 760, 771, 718
```

**Comment by dmi3kno** [comment]
Works for me as well. I think @GreigR was just concerned about the timestamps it returns. It basically returns the timestamp corresponding to last observation for every period, hence, late Saturday night timestamps

**Comment by GreigR** [comment]
Many thanks @dmi3kno <https://github.com/dmi3kno>,

Annoyingly. I get a single count for the total over the whole month, not
one answer per week. Clearly it is some conflict at my end. If you have any
clues please let me know?

Thanks for your help.

Kind regards

Greig
