### ISSUE TITLE
.index synonym for referencing the index

### ISSUE THREAD

**Issue by dmi3kno** [business-science/tibbletime#20]
Hi,
Thanks for the package. You seem to be using different techniques to refer to index in different situations inside functions. Sometimes you simply quote it as symbol (like `index_sym` in `time_summarize`), sometimes you even `dplyr::pull()` it and make it available as vector (like in `index_raw` in `time_filter`).

Wouldn't it be nice to let users safely use `.index` to refer to the index column without ever worrying about the underlying name of the index column?

```
FANG %>% as_tbl_time(index=date) %>%
     mutate(birthday=ifelse(.index==as.Date("2013-01-07"), "my birthday!", "yet another day"))
```
Perhaps `as_tbl_time()` here should also refer to it as `.index` for consistency, but I don't have a strong opinion about it. 

This may actually simplify the interface somewhat. You may not need to provide as many wrappers for standard tidyverse functions, as user can can specify the index manipulation explicitly.

Having said this, I am a bit uncertain about the best way of implementing this (sounds like splicing an argument into the ..., but I am not sure). Sorry for not proposing a PR instead.

**Comment by dmi3kno** [comment]
I think `retrieve_index(x, pull=FALSE)` should return a tibble and with `pull=TRUE` it should return a vector. `get_index(as_name=TRUE)` should return a string (index column name from attributes) and with `as_name=FALSE` it may return a quosure, so you don't have to `sym()` it every time. What do you think?

UPDATE: I would even dare to say that `retrieve_index()` should always return a vector, and `enframe_index()` should return a `tibble`.

Once we implement this, my earlier example would look like the following:

```
FANG %>% as_tbl_time(index=date) %>%
     mutate(birthday=ifelse(retrieve_index(., pull=TRUE)==as.Date("2013-01-07"), 
                 "my birthday!", "yet another day"))
```

Still not sure how to make `.index` a synonym to   `retrieve_index(x, pull=TRUE)` and whether it is worth bothering. Generally speaking, consistency in naming of index would not hurt (I may go as far as to suggest that original column name may need to be stored in attributes and the index column should be always renamed to something generic such as `index` (similar to how `sf`package has `geometry` as a mandatory column for tibble being of `sf` class). The original column name is reinstated upon stripping of `tbl_time` class (e.g. in `as.data.frame()` method).

**Comment by DavisVaughan** [comment]
tibbletime has changed a lot and has some getters for getting the actual index column. They won't work like the `.data` pronouns or anything by having an `.index` pronoun, but they may help. It has also been rewritten in a way where we don't have to implement every `time_*()` function where `*` is `mutate` or `summarise` etc.
