### ISSUE TITLE
summarise by quarter 

### ISSUE THREAD

**Issue by sentieonycdev** [business-science/tibbletime#34]
the following does not actually summarise by quarter - perhaps I'm missing something. I've tried to attach a reproducible code slice. Thank you.

df_slice<-tribble(~filingdate,~keyword,~sum_mentions,
"2017-11-01",".Cloud","2",
"2016-03-22",".NET","4",
"2016-01-26",".That","2",
"2016-11-03","0.5X","2",
"2016-11-03","0.8X","4",
"2016-11-03","0.9X","4",
"2016-04-26","1.1X","2",
"2016-02-09","1.3X","2",
"2016-11-03","1.3X","4",
"2016-02-09","1.5X","2") %>%
mutate(filingdate=as.Date(filingdate)) %>%
mutate(sum_mentions=as.numeric(sum_mentions))

df_slice %>% 
as_tbl_time(filingdate) %>%
group_by(keyword) %>%
time_summarise(period="quarterly",
qtrly_mentions=sum(sum_mentions))

----------------------------
# A time tibble: 10 x 3
# Index: filingdate
# Groups: keyword [9]
keyword filingdate qtrly_mentions
* <chr> <date> <dbl>
1 .Cloud 2017-11-01 2
2 .NET 2016-03-22 4
3 .That 2016-01-26 2
4 0.5X 2016-11-03 2
5 0.8X 2016-11-03 4
6 0.9X 2016-11-03 4
7 1.1X 2016-04-26 2
8 1.3X 2016-02-09 2
9 1.3X 2016-11-03 4
10 1.5X 2016-02-09 2

**Comment by DavisVaughan** [comment]
Two things, 

First, why are you grouping by `keyword`? In this sample dataset, if you group by `keyword` there are no overlapping keyword+filingdate quarter combinations. The only possible one would be `1.3X` but those two rows are in two different quarters so they shouldnt be aggregated together.

Second, if you don't want to group by `keyword` you should order by date. There is no warning currently, but there will be in the next release.

Here is what your dataset looks like if you don't group by keyword. Things are working correctly.

``` r
library(dplyr)
library(tibbletime)


df_slice<-tribble(~filingdate,~keyword,~sum_mentions,
                  "2017-11-01",".Cloud","2",
                  "2016-03-22",".NET","4",
                  "2016-01-26",".That","2",
                  "2016-11-03","0.5X","2",
                  "2016-11-03","0.8X","4",
                  "2016-11-03","0.9X","4",
                  "2016-04-26","1.1X","2",
                  "2016-02-09","1.3X","2",
                  "2016-11-03","1.3X","4",
                  "2016-02-09","1.5X","2") %>%
  mutate(filingdate=as.Date(filingdate)) %>%
  mutate(sum_mentions=as.numeric(sum_mentions))

df_slice %>%
  arrange(filingdate) %>%
  as_tbl_time(filingdate) %>%
  #group_by(keyword) %>%
  time_summarise(period="quarterly",
                 qtrly_mentions=sum(sum_mentions))
#> # A time tibble: 4 x 2
#> # Index: filingdate
#>   filingdate qtrly_mentions
#> * <date>              <dbl>
#> 1 2016-03-22          10.0 
#> 2 2016-04-26           2.00
#> 3 2016-11-03          14.0 
#> 4 2017-11-01           2.00
```

**Comment by sentieonycdev** [comment]
ok, perhaps my sample set was not a good slice of my overall database.  but the end result is i want is filingdate by quarter, keyword, and sum of mentions.  sort of like what you guys do with stock symbols in the vignette.  and in the overall dataset (unfortunately ~15k observations) i get the same issue.  it doesn't aggregate by quarter tho there are clear overlaps.


  filingdate qtrly_mentions
     <date>          <dbl>
1 2017-07-25             26
2 2017-08-09             22
3 2017-09-26             44
4 2017-10-18             44
5 2017-10-31             44
6 2017-11-01             60
7 2017-11-08             46

**Comment by DavisVaughan** [comment]
It should be working right, to demonstrate, I changed the `1.3X` row with date of `"2016-11-03"` to `"2016-02-11"` so that it would fall in the same quarter as the other `1.3X` row. I also floored the filingdate as a new column to show what quarter it belongs in. 

Note that the two `1.3X` rows are combined to give 6

``` r
library(dplyr)
library(tibbletime)

df_slice<-tribble(~filingdate,~keyword,~sum_mentions,
                  "2017-11-01",".Cloud","2",
                  "2016-03-22",".NET","4",
                  "2016-01-26",".That","2",
                  "2016-11-03","0.5X","2",
                  "2016-11-03","0.8X","4",
                  "2016-11-03","0.9X","4",
                  "2016-04-26","1.1X","2",
                  "2016-02-09","1.3X","2",
                  "2016-02-11","1.3X","4",
                  "2016-02-09","1.5X","2") %>%
  mutate(filingdate=as.Date(filingdate)) %>%
  mutate(sum_mentions=as.numeric(sum_mentions))

df_slice %>%
  #arrange(filingdate) %>%
  as_tbl_time(filingdate) %>%
  group_by(keyword) %>%
  time_summarise(period="quarterly",
                 qtrly_mentions=sum(sum_mentions)) %>%
  mutate(filingdate_floored = lubridate::floor_date(filingdate, "quarter"))
#> # A time tibble: 9 x 4
#> # Index: filingdate
#> # Groups: keyword [9]
#>   keyword filingdate qtrly_mentions filingdate_floored
#> * <chr>   <date>              <dbl> <date>            
#> 1 .Cloud  2017-11-01           2.00 2017-10-01        
#> 2 .NET    2016-03-22           4.00 2016-01-01        
#> 3 .That   2016-01-26           2.00 2016-01-01        
#> 4 0.5X    2016-11-03           2.00 2016-10-01        
#> 5 0.8X    2016-11-03           4.00 2016-10-01        
#> 6 0.9X    2016-11-03           4.00 2016-10-01        
#> 7 1.1X    2016-04-26           2.00 2016-04-01        
#> 8 1.3X    2016-02-11           6.00 2016-01-01        
#> 9 1.5X    2016-02-09           2.00 2016-01-01
```

One thing you also might need is the `start_date` parameter. You may want to set this to the first day of the year of the oldest year you have in the dataset. So if your oldest date is `2016-02-04` set it to `2016-01-01`, although I believe this is happening for you already.

**Comment by sentieonycdev** [comment]
filingdate_floored was what i expected filingdate to be mutated TO.  hence my confusion.  thank you - adding that column solves my problem.  hopefully the feedback at least was helpful.  thank you for the prompt response.

**Comment by DavisVaughan** [comment]
Understood! I'd rather use the user's dates directly rather than flooring the dates without telling them. The next version is going to change this workflow quite a bit but it should be more flexible and transparent. Feedback is always welcome! Thanks for posting.
