### ISSUE TITLE
Time series decomposition

### ISSUE THREAD

**Issue by kbzsl** [business-science/tibbletime#35]
Do you plan to add some time series decomposition?

from:  [business-science/tidyquant](https://github.com/business-science/tidyquant/issues/82#issuecomment-352250550)

**Comment by DavisVaughan** [comment]
Is there something specific you can point me to that describes what you want? This package is more focused on manipulating time series tibbles so it might not go here as it feels too specific, but it could go in a different package we may develop in the future.
