### ISSUE TITLE
Is there a way to setup an irregular periodicity or custom period function?

### ISSUE THREAD

**Issue by md0u80c9** [business-science/tibbletime#38]
Hi,

Many thanks for tibbletime - I've just been adapting a quite large project to use it and it's been working brilliantly!

I've had a good look through the documents and I think this is probably a feature request - but I'll ask if it's possible first!

In our project, we have been producing time series on a quarterly basis since 2013. In 2015 we were forced to move to trimesterly reporting, and from 2018 we will be back to quarterly.

So clearly we can describe the time periods with a function - but they are irregular groups of months. I can imagine the project isn't unique for that and many real-world data projects have similar irregularities.

Is there a way to group by period using tibbletime, or to provide a custom function which defines the periodicity? Internally at present as a workaround I use a dplyr::mutate to produce a 'periodNumber' column, but clearly then the time series grouping has to either use tibbletime for months or financial years, but a separate dplyr group on a separate column if the analysis switches to report periods.

Many thanks!

**Comment by DavisVaughan** [comment]
I think I am following what you are saying, but could you flesh it out a bit more with an example? Doesn't have to be perfect, just reproducible so that we can both be on the same page. 

I think this would be a useful feature, and my first thought is to let the `period` argument take a vector of dates that could be used as the groupings or something.

And thanks for the nice words about the package, glad you are finding it useful!

**Comment by md0u80c9** [comment]
Probably the best thing to do is to show you the real-life example: I'm a stroke consultant who does research on the UK national stroke audit.

If you go to www.strokeaudit.org - this is a website where basically we report on the performance of every stroke unit in the UK. We're in the process of migrating the toolset.

On the front of the homepage you'll see a stacked bar chart of national performance over time.

If you look at 2015-7 there is a change of reporting periods from quarterly to trimesterly as with the tools in existence at that time reporting was becoming increasingly onorous. I'm in the process of fully automating the tools before we embark on some more ambitious research.

At the start of the 2018 financial year once it's automated we plan to return to quarterly.


I'm imagining this isn't unusual in time series reporting. Another obvious example might be if you wanted to report based on academic term times (school or Uni) where the terms are irregularly lengthed and will start on different dates each year. You would perhaps want the option to flip between a weekly or monthly view to a 'termly' view in your data visualisation tools.

So I guess the key features I'm describing are:
- You want to be able to set an optional general rule for 'before' your irregular periods.
- You want to set an optional general rule for 'after' them.
- Then you would want to be able to set up one or more 'between' rules where you can tweak the periodicity - whether by a vector or by a function which can specify those rules.

Does that help?

**Comment by DavisVaughan** [comment]
Are you sure it is not 2016-07 rather than 2015-07 where the change happens? From the bar graph on the link you sent, that is where it looks like the dates change. 

Based on the bar graph, I have tweaked `tibbletime` to allow for vectors of endpoints in the `period` argument. This means that you can call `create_series()` a number of times to create your correct endpoints, then pass all that to `collapse_index()` to collapse it in a "custom" way like you want. Does this work for you? (see below)

I think adding some kind of before/after/between rules into the period argument directly might be too specific, and this solution actually renders the `start_date` argument irrelevant because you can create a custom series that would do the same thing (so thanks for that!).

``` r
library(tibbletime)
library(dplyr)

ex_data <- create_series("2013-07-01" ~ "2018-12-31", period = "daily", class = "Date") 
ex_data <- mutate(ex_data, rnorm = rnorm(nrow(ex_data)))

ex_data
#> # A time tibble: 2,010 x 2
#> # Index: date
#>    date        rnorm
#>    <date>      <dbl>
#>  1 2013-07-01  0.424
#>  2 2013-07-02  1.24 
#>  3 2013-07-03 -0.652
#>  4 2013-07-04  1.79 
#>  5 2013-07-05  0.173
#>  6 2013-07-06  0.117
#>  7 2013-07-07  2.85 
#>  8 2013-07-08  0.599
#>  9 2013-07-09  0.889
#> 10 2013-07-10 -0.760
#> # ... with 2,000 more rows

endpoints <- c(
  create_series(time_formula = "2013-07-01" ~ "2016-01-01", period = "quarterly", class = "Date", as_vector = TRUE),
  create_series(time_formula = "2016-04-01" ~ "2017-08-01", period = "4 months",  class = "Date", as_vector = TRUE),
  create_series(time_formula = "2018-01-01" ~ "2018-12-31", period = "quarterly", class = "Date", as_vector = TRUE)
)

endpoints
#>  [1] "2013-07-01" "2013-10-01" "2014-01-01" "2014-04-01" "2014-07-01"
#>  [6] "2014-10-01" "2015-01-01" "2015-04-01" "2015-07-01" "2015-10-01"
#> [11] "2016-01-01" "2016-04-01" "2016-08-01" "2016-12-01" "2017-04-01"
#> [16] "2017-08-01" "2018-01-01" "2018-04-01" "2018-07-01" "2018-10-01"

ex_data %>%
  mutate(date = collapse_index(date, period = endpoints)) %>%
  group_by(date) %>%
  summarise(mean_rnorm = mean(rnorm)) %>%
  print(21)
#> # A time tibble: 20 x 2
#> # Index: date
#>    date       mean_rnorm
#>    <date>          <dbl>
#>  1 2013-09-30    0.342  
#>  2 2013-12-31    0.241  
#>  3 2014-03-31   -0.0179 
#>  4 2014-06-30   -0.0727 
#>  5 2014-09-30    0.00716
#>  6 2014-12-31    0.0536 
#>  7 2015-03-31   -0.0278 
#>  8 2015-06-30    0.0990 
#>  9 2015-09-30   -0.00349
#> 10 2015-12-31   -0.0135 
#> 11 2016-03-31   -0.296  
#> 12 2016-07-31   -0.0598 
#> 13 2016-11-30    0.0256 
#> 14 2017-03-31    0.0826 
#> 15 2017-07-31   -0.116  
#> 16 2017-12-31   -0.171  
#> 17 2018-03-31    0.224  
#> 18 2018-06-30    0.0750 
#> 19 2018-09-30    0.150  
#> 20 2018-12-31    0.0175
```

Created on 2018-01-08 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by md0u80c9** [comment]
Hi,

Yes - you're correct it's 2016 that the change starts!

This looks brilliant - thanks for having a look at this for me! I will look forward to testing it later on!

**Comment by DavisVaughan** [comment]
I've just pushed this to the dev version. The `start_date` argument is now soft-deprecated everywhere, and `period` arguments now take index vectors. You can see the `?as_period` documentation examples ("Using start_date") for information on how it replaces `start_date`. 

Let me know what you think!
  
Install the dev version with:

```r
devtools::install_github("business-science/tibbletime")
```
