### ISSUE TITLE
error under 'assertthat' version 0.1

### ISSUE THREAD

**Issue by jeonghyunwoo** [business-science/tibbletime#4]
when updated to 0.2.0 , error disappeared.
so, below seems to be needed on cran page (https://cran.r-project.org/web/packages/tibbletime/index.html)
'Imports: assertthat   **(≥0.2.0)**, '

**Comment by jeonghyunwoo** [comment]
import packages related errors : (resolved after packages update)
1. when assertthat(0.1) ==> error when FB <- as_tbl_time(FB, index =date)
2. when purrr(0.2.2) ==> error when FANG %>% as_tbl_time(date) %>% tmap_dfc(~mean(.x), period='yearly')

**Comment by DavisVaughan** [comment]
Thanks! I can reproduce what you are saying here.

1) I'll update assertthat (>= 0.2)
2) I'll update purrr (>0.2.3)
3) I'll generally add versions to other packages as well

I dont think that purrr had map_dfc in 0.2.2, not sure what is happening in assertthat without really digging into it.

**Comment by DavisVaughan** [comment]
Fixed by https://github.com/business-science/tibbletime/commit/b85bd32f26f1860ce938e0913752f5167b0f751e
