### ISSUE TITLE
How tibbletime handle the timestamp with milliseconds

### ISSUE THREAD

**Issue by richwu** [business-science/tibbletime#40]
I'm trying to convert a xts object to tibbletime in order to leverage the further functionalities by tibbletime as well as dplyr. Basically, the xts obj is a simple representer of futures tick row data. It looks like this -- 
> head(tstxts)
                      lastPx bidP bidS askP askS totalVol openInt volume deltaOpenInt   tkRtnPct
**2018-01-02 09:00:01.0**   3897 3896   16 3897   33      792  596760    286           -4 0.00000000
**2018-01-02 09:00:01.5**   3899 3899   36 3900  207     1010  596840    218           80 0.05132153
**2018-01-02 09:00:02.0**   3899 3899   51 3900  147     1178  596838    168           -2 0.00000000
**2018-01-02 09:00:02.5**   3900 3899  119 3900   48     1386  596888    208           50 0.02564760
**2018-01-02 09:00:03.0**   3903 3900  123 3903   31     1604  596864    218          -24 0.07692308
**2018-01-02 09:00:03.5**   3907 3908    2 3909   50     2402  596672    798         -192 0.10248527
Warning message:
timezone of object (Asia/Chongqing) is different than current timezone (). 
> class(tstxts)
[1] "xts" "zoo"

And then, I did the following to come up a tibbletime obj
> **as.data.frame(tstxts) %>% mutate(datetime = as.POSIXct(rownames(df), format="%Y-%m-%d %H:%M:%OS")) %>% as_tbl_time(index = 'datetime') %>% head()**
A time tibble: 6 x 11
Index: datetime
  lastPx  bidP   bidS  askP  askS totalVol openInt volume deltaOpenInt tkRtnPct datetime           
  <dbl> <dbl>  <dbl> <dbl> <dbl>    <dbl>   <dbl>  <dbl>        <dbl>    <dbl> <dttm>      
1   3897  3896  16.0   3897  33.0      792  596760    286      -  4.00   0      **2018-01-02 09:00:01**
2   3899  3899  36.0   3900 207       1010  596840    218        80.0    0.0513 **2018-01-02 09:00:01**
3   3899  3899  51.0   3900 147       1178  596838    168      -  2.00   0      **2018-01-02 09:00:02**
4   3900  3899 119     3900  48.0     1386  596888    208        50.0    0.0256 **2018-01-02 09:00:02**
5   3903  3900 123     3903  31.0     1604  596864    218      - 24.0    0.0769 **2018-01-02 09:00:03**
6   3907  3908   2.00  3909  50.0     2402  596672    798      -192      0.102  **2018-01-02 09:00:03**

For the output, **datetime** column, the millisecond by the original timestamp are lost. Did I make this by wrong?

**Comment by DavisVaughan** [comment]
Hey @richwu, I discovered this recently too. This has to do with `tibble` and its underlying printing package, `pillar`. It does not respect the `options(digits.secs)` option and will not print fractional seconds. So this does not have to do with `tibbletime`. 

To prove this:

``` r
library(xts)
library(dplyr)

options(digits.secs = 6)

ex <- xts(1, as.POSIXct("2014-01-01 00:00:00.2"))

ex_df <- as.data.frame(ex)

ex_tbl <- ex_df %>%
  mutate(datetime = as.POSIXct(rownames(ex_df), format="%Y-%m-%d %H:%M:%OS")) %>%
  as_tibble()

ex_tbl
#> # A tibble: 1 x 2
#>      V1 datetime           
#>   <dbl> <dttm>             
#> 1  1.00 2014-01-01 00:00:00

ex_tbl$datetime
#> [1] "2014-01-01 00:00:00.2 EST"
```

Created on 2018-01-09 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

See how even just converting to `tibble` drops the fractional seconds when printing? However, they are still there, and if you are using the development version of `tibbletime` you can still group by millisecond or whatever you need and it should work.

Lastly, I opened an issue on the `pillar` package about this a few days ago (r-lib/pillar#74), hopefully they fix it soon!

**Comment by richwu** [comment]
Hay Davis, 
Thanks for your reply. Very good comments on this problem. I'm happy to know the 'millisec' are not lost in fact, just not support printing on the screen. And I can keep going on tibbletime obj for further analyzing. 
And good to know there is someone taking care of the printing issue as well.
Thanks
Richard
