### ISSUE TITLE
Converting daily data into consistent month or week ends

### ISSUE THREAD

**Issue by tnederlof** [business-science/tibbletime#42]
Something I encounter frequently when looking at instruments in finance across many different markets is the effect of holidays. I often end up with a bunch of daily data (say three different instruments), where if I use `as_period("monthly", side = "end")` and then use spread to pull the data into a wide format I end up with some months were there will be two values (2004-05-28 & 2004-05-31 for example) because one security actually had data on the 31st and the other two did not.

As I am new to the package I wanted to ask if there has been any design thoughts around this type of issue (either way I am happy to try to help). I know a lot of data vendors that will try to have a standardized format so if I want monthly "inline" data, it will pick say the last business day in NYSE holiday schedule and use that for all month ends, essentially aligning the data. I realize it does bring holidays in so maybe this is something to do outside the package?

**Comment by DavisVaughan** [comment]
You could try and ceiling the dates after the call to `as_period()`. That may help. Something like:

```r
ex_data %>%
    as_period("monthly", side = "end") %>%
    mutate(date = ceiling_index(date, "monthly")) %>%
    spread(...)
```

I've toyed with the idea of letting `as_period()` and other functions that take a `period` argument have a `normalize` argument. If true, it looks at the combination of `period` and `side` and performs the rounding for you.

So monthly + end would result in a call to `ceiling_index("monthly")` before returning to the user.
And monthly + start would result in `floor_index("monthly")`

Would that be helpful?

**Comment by tnederlof** [comment]
Yes, those ceiling_index and floor_index functions/wrappers are great thinking, thank you for showing me those. I was able to solve the weekly use case that comes up a lot (want all dates to be on the Friday each week, regardless if some series have a holiday on Friday, etc). Below is an example I cooked up. I will play around with monthly now and see how it works there. Im guessing I am not that unique in wanting to align series together into one consistent set of dates (for weekly Friday to Friday or Thursday to Thursday, etc might be common).
```

daily_data <- structure(list(date = structure(c(17540, 17540, 17539, 17539, 
                                  17536, 17536, 17535, 17535, 17534, 17534, 17533, 17533, 17532, 
                                  17529, 17529, 17528, 17528, 17527, 17527, 17526, 17525, 17522, 
                                  17522, 17521, 17521, 17520, 17520, 17519, 17519, 17518, 17518, 
                                  17515, 17515, 17514, 17514, 17513, 17513, 17512, 17512, 17511, 
                                  17511, 17508, 17508, 17507, 17507, 17506, 17506, 17505, 17505, 
                                  17504), class = "Date"),
               symbol = c("symbol1", "symbol2", "symbol1", "symbol2", "symbol1", "symbol2",
                          "symbol1", "symbol2", "symbol1", "symbol2", "symbol1", "symbol2",
                          "symbol2", "symbol1", "symbol2", "symbol1", "symbol2", "symbol1",
                          "symbol2", "symbol2", "symbol2", "symbol1", "symbol2", "symbol1",
                          "symbol2", "symbol1", "symbol2", "symbol1", "symbol2", "symbol1",
                          "symbol2", "symbol1", "symbol2", "symbol1", "symbol2", "symbol1",
                          "symbol2", "symbol1", "symbol2", "symbol1", "symbol2", "symbol1",
                          "symbol2", "symbol1", "symbol2", "symbol1", "symbol2", "symbol1",
                          "symbol2", "symbol1"), 
               value = c("100.08", "1387.32", "100.41", "1385.78", "100.52", 
                         "1381.81", "100.91", "1378.31", "101.33", "1366.51", "101.55", 
                         "1359.26", "1347.3", "101.41", "1347.3", "101.9", "1349.12", 
                         "101.65", "1344.22", "1340.23", "1335.99", "101.54", "1335.8", 
                         "101.88", "1333.55", "101.43", "1328.34", "101.24", "1324.09", 
                         "101.69", "1330.29", "101.2", "1316.81", "100.49", "1315.18", 
                         "101.19", "1323.38", "100.6", "1321.36", "101.15", "1325.09", 
                         "101.46", "1319.61", "101.89", "1314.01", "101.46", "1306.7", 
                         "102.06", "1315.96", "102.64")),
          .Names = c("date", "symbol", "value"), row.names = c(NA, -50L),
          class = c("tbl_df", "tbl", "data.frame"))


results <- daily_data %>%
  as_tbl_time(index = date) %>%
  arrange(symbol, date) %>%
  group_by(symbol) %>%
  as_period("weekly", side = "end") %>%
  mutate(date = (ceiling_index(date, "weekly") - 2)) %>%
  spread(symbol, value)
```

**Comment by tnederlof** [comment]
Its kind of interesting that when doing monthly it seems to bring me to the 1st of the next month (I confirmed the same result happens with ceiling_date too so it seems to be a lubridate thing). For example...

```
# using the example date in my post above
# the months seem to round 1 day to far (can easily adjust by subtracting 1 though
results <- daily_data %>%
  as_tbl_time(index = date) %>%
  arrange(symbol, date) %>%
  group_by(symbol) %>%
  as_period("monthly", side = "end") %>%
  mutate(date = (ceiling_index(date, "monthly")))
```
