### ISSUE TITLE
Filtering specific time not range

### ISSUE THREAD

**Issue by Hamed51** [business-science/tibbletime#48]
@DavisVaughan @mdancho84 Hello, 
I tried filter specific time by filter_time (). i could not do that. I do not need the range. for example: 
i have a data set from 1990-2016 monthly. I need extract the entire years of  1990,2000 and 2015. how can i filter or extract these three years from my dataset. 
thank you.

**Comment by DavisVaughan** [comment]
`filter_time()` is mainly focused on continuous ranges. I would use `lubridate::year()` for this non-continuous filter.

``` r
library(tibbletime)
#> 
#> Attaching package: 'tibbletime'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date

create_series("1990" ~ "2016", "monthly", "Date") %>%
  filter(year(date) == c(1990, 2000, 2015))
#> # A time tibble: 12 x 1
#> # Index: date
#>    date      
#>    <date>    
#>  1 1990-01-01
#>  2 1990-04-01
#>  3 1990-07-01
#>  4 1990-10-01
#>  5 2000-02-01
#>  6 2000-05-01
#>  7 2000-08-01
#>  8 2000-11-01
#>  9 2015-03-01
#> 10 2015-06-01
#> 11 2015-09-01
#> 12 2015-12-01
```

Created on 2018-02-15 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by Hamed51** [comment]
i use Lubridate as well. Since tibbletime created fast and easy way to handle the time series dataset, i thought there muse be a solution.
Thank  You, 


    On Thursday, February 15, 2018 9:02 AM, Davis Vaughan <notifications@github.com> wrote:
 

 filter_time() is mainly focused on continuous ranges. I would use lubridate::year() for this non-continuous filter.library(tibbletime)
#> 
#> Attaching package: 'tibbletime'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date

create_series("1990" ~ "2016", "monthly", "Date") %>%
  filter(year(date) == c(1990, 2000, 2015))
#> # A time tibble: 12 x 1
#> # Index: date
#>    date      
#>    <date>    
#>  1 1990-01-01
#>  2 1990-04-01
#>  3 1990-07-01
#>  4 1990-10-01
#>  5 2000-02-01
#>  6 2000-05-01
#>  7 2000-08-01
#>  8 2000-11-01
#>  9 2015-03-01
#> 10 2015-06-01
#> 11 2015-09-01
#> 12 2015-12-01Created on 2018-02-15 by the reprex package (v0.1.1.9000).—
