### ISSUE TITLE
dplyr "bind_rows" integration issues

### ISSUE THREAD

**Issue by ghost** [business-science/tibbletime#49]
I was working through some of the same code in the vignette: [using tibbletime with dplyr](https://business-science.github.io/tibbletime/articles/TT-04-use-with-dplyr.html), and noticed a problem with the print method after using `bind_rows` to join two `tbl_time` objects.

```
apple <- create_series('2014' ~ '2016', period = '1 hour') %>%
  mutate(price = 100 + cumsum(rnorm(26304, mean = 0, sd = .5)))

facebook <- create_series('2014' ~ '2016', period = '1 hour') %>%
  mutate(price = 150 + cumsum(rnorm(26304, mean = 0, sd = .5)))

price_series <- bind_rows(list(apple = apple, facebook = facebook), .id = "symbol") # %>%
  #  as_tbl_time(date) %>%
  #  group_by(symbol)

```

The `price_series` assignment above works, but you can't print the object until you run the next step in the pipe, `%>% as_tbl_time`. 

```
R > price_series
Error in eval(expr, envir, enclos) : object '.sep' not found
```

I would think that you want to be ensure that breaking a pipe process at any point allows for inspection.

Thoughts?

**Comment by DavisVaughan** [comment]
Thanks, this is an unfortunate but known bug that has to do with `bind_rows()` not being a generic function. We can't define how it should interact with `tbl_time` objects, and unfortunately it removes attributes but not the `tbl_time` class. This means that when the object is printed, it prints using the `tbl_time` method, but cannot find the `index_quo` attribute required to print correctly. I have an open issue about this on `dplyr`, tidyverse/dplyr#3259, and others have reported similar issues with it not being generic, but I don't know when it will be fixed. The easy solution is to just pipe into `as_tbl_time` again to restore the attributes.

**Comment by ghost** [comment]
Thanks for the response. After posting, it struck me that the issue was likely with `dplyr`. Your response was very helpful and  informative.
