### ISSUE TITLE
example error in 'tmap' function help

### ISSUE THREAD

**Issue by jeonghyunwoo** [business-science/tibbletime#5]
the last example of tmap function  : 
  It is possible to get a cleaner result, but currently not intuitive
   library(tibble)
   FB %>%
      tidyr::gather(key = col_type, value = value, -date) %>%
      dplyr::group_by(col_type) %>%
      tmap_dfr(~quantile(.x) %>% as.list %>% as.tibble, period = "yearly") %>%
      tidyr::unnest()
  **error message:** 
     Error in mutate_impl(.data, dots) : Evaluation error: non-numeric argument to binary operator.

correct example I think: 
   FB %>%
      tidyr::gather(key = col_type, value = value, -date, **-symbol**) %>%
      dplyr::group_by( **symbol**, col_type) %>%
      tmap_dfr(~quantile(.x) %>% as.list %>% as.tibble, period = "yearly") %>%
      tidyr::unnest()

**Comment by DavisVaughan** [comment]
@jeonghyunwoo thanks for this. At the beginning of the Examples section there are the lines:

```r
data(FB)
FB <- as_tbl_time(FB, date)
# No need for the symbol column here
FB <- dplyr::select(FB, -symbol)
```

This would have prevented those problems. I think that each section (divided by the `-----`) should be standalone so this doesnt happen! I'll make the change.
