### ISSUE TITLE
is there a way to use all the timeseries functions with tibbletime

### ISSUE THREAD

**Issue by vikram-rawat** [business-science/tibbletime#50]
There are excellent packages in R which work on timeseries data. each have a different need for different problem. is there a way that I can simply run all those functions with tibbletime. something like when I run a function it changes the data back and forth like a timeseries object and produces result. is it possible now or are you planning to make it possible.

**Comment by DavisVaughan** [comment]
The closest you will ever get to this is to use tidyquant functions which interface xts/quantmod/PerformanceAnalytics/TTR on a tbl_time object (this was recently supported in tidyquant). We will be looking towards creating our own extension packages that offer support for financial applications, and we will be looking at ways to extend the `forecast` package to work with tbl_time objects, but other than that we don't plan on doing the conversion idea any more. Its very slow
