### ISSUE TITLE
Simple join support

### ISSUE THREAD

**Issue by md0u80c9** [business-science/tibbletime#54]
Doing some testing today, I think I'm right in thinking that if you do any sort of join, the output is a tibble, not a tbl_time, even if you haven't affected the indexing. In my current workflow that may mean re-indexing the resulting tibbles possibly multiple times.

I wondered whether it would be possible to support very basic join operations, such as preserving the tbl indexing on:

- Inner joins (which will be lossy but shouldn't affect the index).
- Left / Right joins where the tbl_time and indexed field is on the 'to one' side.

In both those cases we shouldn't have affected the index at all.

Appreciating the earlier feature discussion of more complete implementations which would be lovely but clearly more complex to implement.

**Comment by DavisVaughan** [comment]
The `x` argument (LHS) of the join should always determine what the resulting output is. You can see that the first two examples below remain tbl_time but the last one has a `x` that is just a tibble and a `y` that is tbl_time. In that case the result is tibble

``` r
library(tibbletime)
library(dplyr)
options(tibble.print_min = 5)
data(FB)

FB_time <- FB %>% as_tbl_time(date)

FB_open <- FB_time %>% select(date, open)
FB_close <- FB_time %>% select(date, close)

FB_open_tbl <- as_tibble(FB_open)
FB_close_tbl <- as_tibble(FB_close)

left_join(FB_open, FB_close)
#> Joining, by = "date"
#> # A time tibble: 1,008 x 3
#> # Index: date
#>   date        open close
#>   <date>     <dbl> <dbl>
#> 1 2013-01-02  27.4  28.0
#> 2 2013-01-03  27.9  27.8
#> 3 2013-01-04  28.0  28.8
#> 4 2013-01-07  28.7  29.4
#> 5 2013-01-08  29.5  29.1
#> # ... with 1,003 more rows

left_join(FB_open, FB_close_tbl)
#> Joining, by = "date"
#> # A time tibble: 1,008 x 3
#> # Index: date
#>   date        open close
#>   <date>     <dbl> <dbl>
#> 1 2013-01-02  27.4  28.0
#> 2 2013-01-03  27.9  27.8
#> 3 2013-01-04  28.0  28.8
#> 4 2013-01-07  28.7  29.4
#> 5 2013-01-08  29.5  29.1
#> # ... with 1,003 more rows

left_join(FB_open_tbl, FB_close)
#> Joining, by = "date"
#> # A tibble: 1,008 x 3
#>   date        open close
#>   <date>     <dbl> <dbl>
#> 1 2013-01-02  27.4  28.0
#> 2 2013-01-03  27.9  27.8
#> 3 2013-01-04  28.0  28.8
#> 4 2013-01-07  28.7  29.4
#> 5 2013-01-08  29.5  29.1
#> # ... with 1,003 more rows
```

**Comment by md0u80c9** [comment]
Ah - that's fantastic, thank you! I think my tbl_time was on the RHS which is why I hadn't spotted that this works!
