### ISSUE TITLE
Question: Missing "step" argument for rollify?

### ISSUE THREAD

**Issue by Fritzimponis** [business-science/tibbletime#62]
In my experience rolling calculations include mainly two parameters; step and window. An example of this is calculating a rolling 5 year (window) return every 1 year (step) on daily data. I suspect there is a reason for step not included in the function arguments. Could you please explain what the that could be?

Thanks

**Comment by DavisVaughan** [comment]
tibbletime is now retired, and will not receive active development. Have a look at {slide} for more sliding functions and the ability to specify a `.step` argument https://davisvaughan.github.io/slide/index.html
