### ISSUE TITLE
rollify for partial windows

### ISSUE THREAD

**Issue by cdeterman** [business-science/tibbletime#63]
Currently, if I use `rollify` with a `window=5`, as an example, the first 4 elements are `NA` values.  Is there anything similar to the `zoo::rollapplyr` function with the `partial` argument?

**Comment by cdeterman** [comment]
Any thoughts regarding this?  I'm not sure how active this package development is given I only just recently saw the Rstudio video.

**Comment by giovanni-prestipino** [comment]
Any thoughts regarding this?

**Comment by DavisVaughan** [comment]
As noted in the README now, tibbletime is retired in favor of tsibble. I would encourage you to switch over. They have this functionality with the `.partial` argument I believe https://github.com/tidyverts/tsibble/blob/master/R/slide.R#L58

**Comment by giovanni-prestipino** [comment]
thank you!!!!!

**Comment by DavisVaughan** [comment]
Also see the new package I have been working on, {slide}, which is eventually going to replace tsibble's sliding functions. The last example here also discusses partial sliding https://davisvaughan.github.io/slide/reference/slide.html
