### ISSUE TITLE
Multiple Rolling Calculations

### ISSUE THREAD

**Issue by mdancho84** [business-science/tibbletime#64]
Add function to produce multiple rolling calculations. Here is a basic version, multi_roller(), but it would be nice to have it work with groups as well. 

    multi_roller <- function(data, col, ..f = mean, 
                         window = c(10, 20, 30, 100, 200), sep = "V_") {
    
    col_expr <- enquo(col)
    
    ret_tbl <- window %>%
        set_names(~ paste0(sep, window)) %>%
        map_dfc(~ rollify(..f, window = .x)(pull(data, !! col_expr))) %>%
        bind_cols(data, .)
    
    return(ret_tbl)
    
    }

**Comment by DavisVaughan** [comment]
Easier to just use slider, I think https://github.com/DavisVaughan/slider

Something like

```r
library(slider)
library(purrr)
#> Warning: package 'purrr' was built under R version 3.6.2

multi_slide_dbl <- function(.x, .f, .befores) {
  slide_before <- function(before) {
    slide_dbl(.x, .f, .before = before)
  }
  map(.befores, slide_before)
}

multi_slide_dbl(1:5, mean, c(2, 3, 4))
#> [[1]]
#> [1] 1.0 1.5 2.0 3.0 4.0
#> 
#> [[2]]
#> [1] 1.0 1.5 2.0 2.5 3.5
#> 
#> [[3]]
#> [1] 1.0 1.5 2.0 2.5 3.0
```
