### ISSUE TITLE
rollify() using larger window than length of data

### ISSUE THREAD

**Issue by JerryWho** [business-science/tibbletime#65]
Sometimes the size of one group of my data is smaller than the window size. rollify() throws an error and exits.
I suggest the return the length of data with na_value (as the beginning of the return value with larger data sizes). 
I've tried to implement this. I'll send you a pull request. Maybe you can use it.

**Comment by DavisVaughan** [comment]
See https://github.com/business-science/tibbletime/pull/66#issuecomment-533367049
