### ISSUE TITLE
filter_time error  in rlang 0.2.1

### ISSUE THREAD

**Issue by killereco** [business-science/tibbletime#67]
> FB <- as_tbl_time(FB, index = date)
> FB %>% filter_time('2013-03' ~ '2015')
Error in filter_impl(.data, quo) : 
  Evaluation error: Incorrect number of arguments (5), expecting 4 for 'rlang_tilde_eval'.

**Comment by DavisVaughan** [comment]
I can't reproduce this with the most recent tibbletime and rlang
