### ISSUE TITLE
ERROR: compilation failed for package 'tibbletime'

### ISSUE THREAD

**Issue by Hellengeremias** [business-science/tibbletime#69]
Dear all,

I am trying to install tibbletime but the following error is presented:

devtools::install_github("business-science/tibbletime")
Downloading GitHub repo business-science/tibbletime@master
from URL https://api.github.com/repos/business-science/tibbletime/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.4,3.5)

Any help would be much apreciated.

Best regards,
Hellen

**Comment by DavisVaughan** [comment]
Hi Hellen, it looks like you are on Windows and have R 3.5.1. This seems to be a `devtools` related error connected to this issue:
https://github.com/r-lib/devtools/issues/1772

I would suggest updating `devtools` to the development version, and maybe also installing `pkgbuild` as well just to ensure you have it. 

If that doesn't work, I would try reinstalling the latest version of RTools from here:
https://cran.r-project.org/bin/windows/Rtools/

**Comment by Hellengeremias** [comment]
Thank you @DavisVaughan!

I updated devtools and reinstalled Rtools 3.5.
After that, tibbletime installation was completed successfully :)
