### ISSUE TITLE
Error: Must pass a scalar integer as `nrow` argument to `new_tibble`

### ISSUE THREAD

**Issue by mingsu** [business-science/tibbletime#74]
`library(tibbletime)`
Attaching` package: ‘tibbletime’
The following object is masked from ‘package:stats’:

filter

`data(FB)`
` FB <- as_tbl_time(FB, index = date)`
Error: Must pass a scalar integer as `nrow` argument to `new_tibble()`.
Call `rlang::last_error()` to see a backtrace

`sessionInfo()`
#> R version 3.3.3 (2017-03-06)
#> Platform: x86_64-apple-darwin13.4.0 (64-bit)
#> Running under: macOS  10.14

#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base

#> other attached packages:
#> [1] tibbletime_0.1.1.9000 nvimcom_0.9-75        setwidth_1.0-4        colorout_1.1-2

#> loaded via a namespace (and not attached):
#> [1] Rcpp_1.0.0         tidyr_0.8.2        crayon_1.3.4       dplyr_0.7.8        assertthat_0.2.0   R6_2.2.2
#>  [7] magrittr_1.5       pillar_1.3.1.9000  rlang_0.3.0.9002   bindrcpp_0.2.2     tools_3.3.3        glue_1.3.0
#> [13] purrr_0.2.5        pkgconfig_2.0.2    tidyselect_0.2.5   bindr_0.1.1        tibble_1.4.99.9006`

**Comment by DavisVaughan** [comment]
should be fixed by #73
