### ISSUE TITLE
Collapse_index with unordered index fails

### ISSUE THREAD

**Issue by md0u80c9** [business-science/tibbletime#75]
Hi,

I've been trying to investigate an issue with my code around a bug present when I use monthly groupings.

I didn't reproduce it exactly, but I did write this quick test:

```
> test_tibble <- tibble::tribble(~name, ~date, "Bob", as.Date("2017-10-05"), "Jim", as.Date("2017-10-09"), "Sheila", as.Date("2017-08-03"))
> test_tm_tbl <- tibbletime::as_tbl_time(test_tibble, date)
> tibbletime::collapse_index(test_tm_tbl[["date"]],
+     period = "1 m",
+     side = "start",
+     clean = TRUE)

```

Which fails with the error: "Error: Incorrect expanded time_formula. `from`, 2017-10-01, must be before `to`, 2017-09-01"

If you add the start_date, this will work:

```
tibbletime::collapse_index(test_tm_tbl[["date"]],
+     period = "1 m", start_date = as.Date("2017-08-01"),
+     side = "start",
+     clean = TRUE)
```

Is it assuming that the dates have to be ordered before the collapse_index is performed if we don't specify the start_date?

Not sure if that's actually the problem I found in my code.

Also - I'm using tibble v2.0.1 - I've noticed there is a pull request outstanding for this from the tibble developers - not sure if this will affect this issue or not.

**Comment by md0u80c9** [comment]
I don't have a repress for the issue, but the actual problem I'm hunting (which may or may not be related to the above), is with this piece of code:

check_start_date <- dplyr::mutate(
+     cohort,
+     ReportPeriod = tibbletime::collapse_index(
+         as.Date(.data[[period_date_field]]),
+         period = "1 m",
+         side = "start",
+         clean = TRUE))
Error in mutate_impl(.data, dots) : 
  Evaluation error: missing value where TRUE/FALSE needed.

If I run this same line of code with either an irregular time period setup in the period parameter, or with financial years (April-April of each year), then the code works absolutely fine - ie. varying period appears to determine whether the code passes or fails.

**Comment by DavisVaughan** [comment]
I don't have much time at all to spend on `tibbletime` any more, and really recommend looking at `tsibble` because that is where the great work is being done now. In this case, I can say for certain that tibbletime expects dates to be in ascending order for pretty much every operation. Most of the time it warns you if they are not, but I may have missed a case here.

**Comment by md0u80c9** [comment]
For reference the actual issue I was originally investigating when I raised this (further down) were addressed by your new release on CRAN which contained the fix for the new version of tibble.
