### ISSUE TITLE
Adjust to dev tidyr, slated to become v1.0.0

### ISSUE THREAD

**Issue by jennybc** [business-science/tibbletime#79]
We see problems in tidyr revdep checks:

https://github.com/tidyverse/tidyr/blob/master/revdep/problems.md#tibbletime

Fixing this has high leverage, because resolving this in tibbletime might also resolve problems in anomalize:

https://github.com/tidyverse/tidyr/blob/master/revdep/problems.md#anomalize

**Comment by jennybc** [comment]
cc @DavisVaughan

**Comment by DavisVaughan** [comment]
Fixed in #80, submitting to cran asap
