### ISSUE TITLE
Incorporate `time_left_join`

### ISSUE THREAD

**Issue by DavisVaughan** [business-science/tibbletime#8]
because this just doesnt work right with 2017-09-06/07

```r
stocks <- tq_get(c("MSFT", "SPY"), from = "2012-01-01", to = "2017-09-07") %>%
  group_by(symbol) %>%
  tq_transmute(adjusted, monthlyReturn) %>%
  as_tbl_time(date) %>%
  time_collapse("monthly")

risk_free <- tq_get("DGS1MO", get = "economic.data", from = "2012-01-01", to = "2017-09-07") %>%
  as_tbl_time(date) %>%
  as_period("monthly", side = "end")

left_join(stocks, risk_free, "date")
```

**Comment by dmi3kno** [comment]
What exactly did not work here? was the problem in `time_collapse()`? Could it be that I accidentally fixed it, because it works for me, after PR #23 
What we could do is try to build (somewhat slow) rolling join:

```
# retrieve two stocks and extract quotes every 3 months
stocks3m <- tq_get(c("MSFT", "SPY"), from = "2012-01-01", to = "2017-09-07") %>%
  group_by(symbol) %>%
  tq_transmute(adjusted, monthlyReturn) %>%
  as_tbl_time(date) %>%
  time_summarise(3~m) %>% 
  ungroup()

stocks3m %>% arrange(date) %>% head()
># A time tibble: 6 x 2
># Index: date
>  symbol       date
>*  <chr>     <date>
>1   MSFT 2012-03-30
>2    SPY 2012-03-30
>3   MSFT 2012-06-29
>4    SPY 2012-06-29
>5   MSFT 2012-09-28
>6    SPY 2012-09-28

# retrieve interest rate quotes for every 2 months
riskfree2m <- tq_get("DGS1MO", get = "economic.data", from = "2012-01-01", to = "2017-09-07") %>%
  as_tbl_time(date) %>%
  as_period(2~m, side="end")

riskfree2m %>% arrange(date) %>% head()
># A time tibble: 6 x 2
># Index: date
>        date price
>*     <date> <dbl>
>1 2012-02-29  0.08
>2 2012-04-30  0.07
>3 2012-06-29  0.04
>4 2012-08-31  0.09
>5 2012-10-31  0.09
>6 2012-12-31  0.02

left_join_timeroll<-function(x, y){
# function for "rolling join" by index (therefore does not require `by` argument
  
  index_char_x     <- retrieve_index(x, as_name = TRUE)
  index_sym_x      <- rlang::sym(index_char_x)
  index_tbl_x      <- retrieve_index(x)
  all_cols_char_x  <- setdiff(colnames(x), index_char_x)
  all_cols_syms_x  <- rlang::syms(all_cols_char_x)
  
  index_char_y     <- retrieve_index(y, as_name = TRUE)
  index_sym_y      <- rlang::sym(index_char_y)
  all_cols_char_y  <- setdiff(colnames(y), index_char_y)
  all_cols_syms_y  <- rlang::syms(all_cols_char_y)
  
# create grid with all possible (x and y) dates and fill down y columns
  filled_y_grid <- full_join(index_tbl_x, y, by=(index_char_x=index_char_y)) %>% 
    distinct() %>% 
    arrange(!! index_sym_x) %>% 
    tidyr::fill(!!!all_cols_syms_y) 

# join in x columns
  left_join(x, filled_y_grid, by= index_char_x) %>% 
    select(!!index_sym_x, everything())
}

# do rolling join. Arranged by date, so it is easy to see whats going on.
left_join_timeroll(stocks3m, riskfree2m) %>%
  arrange(date) %>% head()
# A time tibble: 6 x 3
# Index: date
#        date symbol price
#*     <date>  <chr> <dbl>
#1 2012-03-30   MSFT  0.08
#2 2012-03-30    SPY  0.08
#3 2012-06-29   MSFT  0.04
#4 2012-06-29    SPY  0.04
#5 2012-09-28   MSFT  0.09
#6 2012-09-28    SPY  0.09
```
Why is right_join() not working?

**Comment by DavisVaughan** [comment]
The problem was not that it gave an error, just that it gave results that you wouldn't expect. Consider row 69 of the example after you `left_join()`. It should be:

```r
> slice(ex, 69)
# A time tibble: 2 x 4
# Index:  date
# Groups: symbol [2]
  symbol       date monthly.returns price
*  <chr>     <date>           <dbl> <dbl>
1   MSFT 2017-09-06    -0.018322791    NA
2    SPY 2017-09-06    -0.002383982    NA
```

Ideally, when joining by month the price column would have a value here. The reason it does not is because the date for year 2017, month 9 for the price column is:

```r
> risk_free[~2017-09]
# A time tibble: 1 x 2
# Index: date
        date price
*     <date> <dbl>
1 2017-09-07  0.98
```

The `2017-09-06` and `2017-09-07` don't line up so they don't join.

`time_left_join` would let you join by month, which would in theory only look at `2017-09` and join off that.

**Comment by DavisVaughan** [comment]
_Why is right_join() not working?_ 

^ Because i still haven't added support for it haha. `dplyr` drops classes/attributes automatically when using functions like that. I've supported alot of them but not all. I'll add support for right join soon.

**Comment by dmi3kno** [comment]
Thanks for your answer. Joining monthly data by month makes sense. In `time_collapse()` or `time_summarize()` you could specify that you want to disregard the day information (say, set it to 1st of the month).

Since we are addressing time tibbles here, I thought making an attempt at re-implementing rolling joins (even a slow version of it) would make a difference. Right now [the most straightforward solution](https://stackoverflow.com/questions/24480031/roll-join-with-start-end-window) seems to be using `data.table`. Hadley is [hesitant](https://github.com/tidyverse/dplyr/issues/378) of adding it to dplyr, but anyone working with time data will encounter it sooner or later.

Isn't `right_join()` just a copy of a few functions with a small modification? Would you mind if I take a shot at it?

**Comment by DavisVaughan** [comment]
`right_join` is easy. ill put up a patch today. just look at what i do with [`left_join`](https://github.com/business-science/tibbletime/blob/master/R/dplyr-left_join.R)

**Comment by DavisVaughan** [comment]
`In time_collapse() or time_summarize() you could specify that you want to disregard the day information (say, set it to 1st of the month).` 

^ this has potential. I definitely dont want to do this by default because i dont want the user to lose that data automatically. But it would help with joins and there would be no need for a time join function.

However, if the user does want to join two datasets together by month that might have different days, AND they want to keep the information about the days, then they are out of luck because the time_collapse would remove the info about the days.

It would look something like:

```r
AAPL <- time_collapse("monthly", normalize_to_period = TRUE)

FB %>%
     time_collapse("monthly", normalize_to_period = TRUE) %>%
     left_join(AAPL)
```

Or just `normalize`

**Comment by dmi3kno** [comment]
I intend to build upon the package using annual data, so my index will always look like `2012-01-01`, `2013-01-01`, `2014-01-01`, etc. Ideally I see a potential for using integers as index (because ts allows it). 

In your example above, you would ideally like to have Date-related class that carries only year and month information (like `zoo::yearmon`). I am sure you have an opinion about using `zoo` objects as indices, so I am not going to insist. `normalize` argument seems to do the trick here.

Generally speaking, you could think of "aggregation joins" - like the seconds data that is join on minutes/hours/days/months, etc. So it could be done with `period` argument inside the `_join.tbl_time()` family. I would rather extend existing verbs than come up with our own.

**Comment by DavisVaughan** [comment]
_I am sure you have an opinion about using zoo objects as indices_. It's not so much that I don't want to use them, it's just that right now I'd like to limit the number of different types of date classes that I have to manage. Maybe one day. 

It was definitely a design choice that I thought about for awhile, and finally decided Date/POSIXct make up most of the use cases, are native classes, and work consistently enough that they are mostly interchangeable in terms of programming around them. 

I do agree that having to do `2013-01-01` over `2013` kind of sucks. Maybe there can be support for integers as the index one day.

**Comment by DavisVaughan** [comment]
_Since we are addressing time tibbles here, I thought making an attempt at re-implementing rolling joins (even a slow version of it) would make a difference. Right now the most straightforward solution seems to be using data.table. Hadley is hesitant of adding it to dplyr, but anyone working with time data will encounter it sooner or later._

Can you open a separate issue with information about this? I'm not that familiar with rolling joins. If they provide a helpful tidyverse alternative to data.table then I'm happy to look into them

**Comment by DavisVaughan** [comment]
_Generally speaking, you could think of "aggregation joins" - like the seconds data that is join on minutes/hours/days/months, etc. So it could be done with period argument inside the _join.tbl_time() family. I would rather extend existing verbs than come up with our own._

I like this idea. maybe instead of `time_left_join(period = "monthly")`, just `left_join.tbl_time(period = "monthly")`. But what happens if we just want to use a regular left join on a `tbl_time` and no period is supplied?

`if(period = NULL) then NextMethod()` is a possibility to just pass the info along to `left_join.tbl_df()`

**Comment by dmi3kno** [comment]
yes, `left_join(period=NULL)` should be the default and then you would see NAs as in your very first example. 
You probably should send to NextMethod() if `period` is among the user-specified arguments.
