### ISSUE TITLE
Feature Request: Expanding Window, vector for window

### ISSUE THREAD

**Issue by rjvelasquezm** [business-science/tibbletime#86]
Would be great if rather than a fixed window we could submit either an expanding window or a vector of window length for each calculation.

For example with rollapply you're able to set a vector as a window instead of a single value.

**Comment by DavisVaughan** [comment]
Please use slider instead. It supports expanding windows with `slide(.before = Inf)` and you could probably construct a vector of windows with `hop()` https://github.com/DavisVaughan/slider

tibbletime is retired in favor of tsibble and is no longer actively maintained https://github.com/tidyverts/tsibble
