### ISSUE TITLE
Ensure github pages deployment is working

### ISSUE THREAD

**Issue by DavisVaughan** [business-science/tibbletime#88]
@mdancho84 can you please go into the Settings on this repo, scroll all the way down in Options, and ensure that Github Pages is deploying from the gh-pages branch?

**Comment by mdancho84** [comment]
@DavisVaughan Just changed to gh-pages. Let me know if it works.

**Comment by mdancho84** [comment]
Looks like we're getting a 404

**Comment by DavisVaughan** [comment]
That means it worked actually, just sent a commit that should fix it in a few minutes

**Comment by mdancho84** [comment]
OK, sounds good. Thanks for your work on `hardhat` too. Making `modeltime` easy to set up. Should be an interesting addition for the time series folks.

**Comment by DavisVaughan** [comment]
Docs are building again. And thanks! Glad it is helping
