### ISSUE TITLE
Dropping NA values reverts a tibbletime object to a tibble object

### ISSUE THREAD

**Issue by nitingupta2** [business-science/tibbletime#94]
Recently started using tibbletime. Noticed that a tibbletime object reverts to a tibble object if NA values are dropped in a time series.
I understand tibbletime objects are indexed by date-time. Could indices be redone with remaining index values when `drop_na` is used? 

Here's an example of what's happening:

![image](https://user-images.githubusercontent.com/7339049/87274186-26576400-c4a9-11ea-81c3-c853b90e3d72.png)
Clearly here `drop_na()` could been done before casting `df` to tibbletime object. But in a practical world for instance, the original `df` object could've been used for plotting all values of individual series. Then NA values could've been dropped downstream for computing portfolio returns, which in this case would require recasting `df` to a tibbletime object again, if its properties were to be used.

**Comment by DavisVaughan** [comment]
tibbletime has been formally retired in favor of tsibble. It will not receive any features besides bug fixes to keep it on CRAN. I would encourage you to please use tsibble instead! https://github.com/tidyverts/tsibble
