### ISSUE TITLE
Will tibbletime enventually be completely superseeded by tsibble and timek?

### ISSUE THREAD

**Issue by GitHunter0** [business-science/tibbletime#98]
Will `tibbletime ` enventually be completely superseeded by `tsibble `and `timek `or some functions like `as_period()` will continue to live solely inside `tibbletime`?

Thank you, your packages are awesome.

**Comment by DavisVaughan** [comment]
It is already retired, and no new features will be added!

If the other packages can't do something that tibbletime can, I would recommend opening up an issue on their respective github repos.

**Comment by GitHunter0** [comment]
Ok @DavisVaughan , I could not find something like `as_period()` in other packages, so I will do what you suggested.
